# Generated by Django 5.0.2 on 2024-03-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Debtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('phone_numuber', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=5, max_digits=11)),
                ('product', models.ManyToManyField(to='product.product')),
            ],
        ),
    ]
