# Generated by Django 5.0.2 on 2024-03-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtors',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
    ]
