# Generated by Django 5.0.1 on 2024-03-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtors',
            name='product',
        ),
        migrations.AlterField(
            model_name='debtors',
            name='phone_numuber',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
